// RenderStoredPage.tsx
//
// This is what a real page (e.g. app/[slug]/page.tsx) would do after
// fetching from your database. Note there's NO import of HeroView or
// any layout component here — the "layout" is already baked into the
// stored HTML from when it was authored. Rendering is just injection.

import React from 'react';
import type { StoredSection } from '../page';

export function RenderStoredPage({ sections }: { sections: StoredSection[] }) {
  return (
    <div className="space-y-2">
      {sections.map((sec) => (
        // eslint-disable-next-line react/no-danger
        <div key={sec.id} data-section-type={sec.type} dangerouslySetInnerHTML={{ __html: sec.html }} />
      ))}
    </div>
  );
}

// Example of the fetch step this would sit behind:
//
// export default async function PublicPage({ params }: { params: { slug: string } }) {
//   const page = await db.pages.findBySlug(params.slug); // { sections: StoredSection[] }
//   return <RenderStoredPage sections={page.sections} />;
// }
//
// Caveat: dangerouslySetInnerHTML is safe here only because the HTML
// was generated by your own editor (page.tsx), not user-submitted
// free text. If sections could ever contain arbitrary user HTML from
// an untrusted source, sanitize on the way in (e.g. with DOMPurify)
// before it's stored, not just on the way out.